gcc -o mqtt Base64.c \
            Clients.c \
            Heap.c \
            LinkedList.c \
            Log.c \
            Messages.c \
            MQTTPacket.c \
            MQTTPacketOut.c \
            MQTTPersistence.c \
            MQTTPersistenceDefault.c \
            MQTTProperties.c \
            MQTTProtocolClient.c \
            MQTTProtocolOut.c \
            MQTTReasonCodes.c \
            MQTTTime.c \
            Proxy.c \
            SHA1.c \
            Socket.c \
            SocketBuffer.c \
            StackTrace.c \
            Thread.c \
            Tree.c \
            utf-8.c \
            WebSocket.c \
            MQTTClient.c \
            main.c -lpthread